//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kapustinRPMBD18
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterPieceAccounting
    {
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string ThirdName { get; set; }
        public string WorkshopName { get; set; }
        public string WorkshopBossName { get; set; }
        public Nullable<int> WorkersCount { get; set; }
        public Nullable<int> ACount { get; set; }
        public Nullable<int> BCount { get; set; }
        public Nullable<int> CCount { get; set; }
    }
}
